name: Build page

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ssh_key: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Build page
        run: bundle exec jekyll build

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ env.ssh_key }}
      - name: rsync to target
        run: rsync -Pr -e "ssh -o StrictHostKeyChecking=accept-new" _site/ agdj@agdj.uber.space:/var/www/virtual/agdj/2023.allegutendinge.jetzt
